/*

 MAPGAME.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 40 x 18
   Tile set      : C:\Users\lucap\Documents\GB\gbtd22\Stick.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define StickMapWidth 40
#define StickMapHeight 18
#define StickMapBank 0

extern unsigned char StickMap[];

/* End of MAPGAME.H */
